baseURL: "https://bertilledaran.github.io/"
title: Bertille Daran
theme: PaperMod
copyright: "Bertille Daran"

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
  tag: tags

menu:
  main:
    - name: Research
      url: research/
      weight: 10
    - name: Teaching
      url: teaching/
      weight: 20
    - name: Talks
      url: talks/
      weight: 30

params:
  description: "Academic website of Bertille Daran, PhD candidate in environmental economics."
  author: Bertille Daran
  DateFormat: "January 2006"
  defaultTheme: light
  hideFooter: false
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: false
  MainSections: ["research", "teaching", "talks"]
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: true
  profileMode:
    enabled: true
    title: Bertille Daran
    subtitle: "I am an **environmental economist** with a PhD from Institut Polytechnique Paris ([manuscript](/jmp.pdf), slides), graduated in February 2026.  <b> My research focuses on the interdependencies between *international flows*, both economic and human, and *land cover and land use*. My thesis addresses three dimensions of climate diplomacy: negotiations, cooperation, and finance. I use quantitative spatial models and advanced econometric techniques, combining them with complementary methods such as natural language processing and elite surveys.  <b> I will begin a position as a postdoctoral fellow at Université Paris Dauphine-PSL in Fall 2026.  \n\nFeel free to reach out by [email](mailto:bertille.daran@sciencespo.fr)."
    imageUrl: "profile.jpg"
    imageWidth: 180
    imageHeight: 180
    buttons:
      - name: Research
        url: research/
      - name: Teaching
        url: teaching/
      - name: Talks
        url: talks/
  socialIcons:
    - name: CV
      url: cv/
    - name: Email
      url: mailto:bertille.daran@sciencespo.fr
    - name: Location
      url: location/
    - name: Google Scholar
      url: https://scholar.google.fr/citations?user=3dGN0zEAAAAJ&hl=fr&oi=ao
    - name: GitHub
      url: https://github.com/bertilledaran
    - name: LinkedIn
      url: https://linkedin.com/in/bertille-daran
  assets:
    disableScrollBarStyle: true
  cover:
    hiddenInList: true
    hiddenInSingle: true
  label:
    text: "Bertille Daran"
    icon: favicon.ico
    iconHeight: 18

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: autumn
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
